# Generated by Django 3.0.7 on 2020-07-23 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_auto_20200720_1207"),
    ]

    operations = [
        migrations.AlterField(model_name="user", name="username", field=models.CharField(max_length=150),),
    ]
