# Generated by Django 3.0.7 on 2020-07-27 23:52

from django.db import migrations

import users.models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_auto_20200723_2133"),
    ]

    operations = [
        migrations.AlterModelManagers(name="user", managers=[("objects", users.models.UserManager())],),
    ]
