version: "3.7"

services:
  superlists:
    container_name: superlists
    build: .
    volumes:
    - "/srv/sites/$DOMAIN:/src/superlists/data"
    labels:
    - "traefik.enable=true"
    - "traefik.http.routers.superlists.entryPoints=https"
    - "traefik.http.routers.superlists.rule=Host(`$DOMAIN`)"

  nginx:
    container_name: nginx
    image: nginx:1.19.0
    volumes:
    - "./nginx.conf:/etc/nginx/conf.d/superlists.conf:ro"
    - "/srv/sites/$DOMAIN/static:/srv/superlists/static:ro"
    labels:
    - "traefik.enable=true"
    - "traefik.http.routers.nginx.entryPoints=https"
    - "traefik.http.routers.nginx.rule=Host(`$DOMAIN`) && PathPrefix(`/static/`)"
    - "traefik.http.services.nginx.loadbalancer.server.port=8000"

networks:
  default:
    external: true
    name: traefik
