version: "3.7"

services:
  traefik:
    container_name: traefik
    image: traefik:v2.2.1
    command:
    - "--accesslog=true"
    - "--providers.docker=true"
    - "--providers.docker.exposedbydefault=false"
    - "--entrypoints.https.address=:443"
    - "--entrypoints.https.http.tls.certresolver=tls-resolver"
    - "--entrypoints.http.address=:80"
    - "--entrypoints.http.http.redirections.entryPoint.to=https"
    - "--certificatesresolvers.tls-resolver.acme.tlschallenge=true"
    #    - "--certificatesresolvers.tls-resolver.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory"
    - "--certificatesresolvers.tls-resolver.acme.email=$EMAIL"
    - "--certificatesresolvers.tls-resolver.acme.storage=/letsencrypt/acme.json"
    ports:
    - "80:80"
    - "443:443"
    volumes:
    - "/var/run/docker.sock:/var/run/docker.sock:ro"
    - "/srv/letsencrypt:/letsencrypt"
    networks:
    - traefik

networks:
  traefik:
    name: traefik

