# Generated by Django 3.0.7 on 2020-06-25 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lists", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(model_name="item", name="text", field=models.TextField(default=""),),
    ]
