# Generated by Django 3.0.7 on 2020-07-13 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lists", "0003_auto_20200629_1430"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="item", constraint=models.UniqueConstraint(fields=("text", "list"), name="unique_text_list"),
        ),
    ]
